type: default-flatpaks

notify: true # Send notification after install/uninstall is finished (true/false)

system:
  install:
    - com.discordapp.Discord
    - com.spotify.Client
    - org.vinegarhq.Vinegar
    - org.gnome.Boxes
    - us.zoom.Zoom
    - org.mozilla.firefox
    - io.gitlab.librewolf-community
    - tv.plex.PlexDesktop
    - io.github.dvlv.boxbuddyrs
    - com.github.tchx84.Flatseal
    - net.lutris.Lutris
    - com.github.Matoking.protontricks
    - net.davidotek.pupgui2
    
  remove: